"""created_relationships_of_books.py

Revision ID: 0f21c1eb72db
Revises: f77b45958907
Create Date: 2026-08-24 17:42:42.388952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f21c1eb72db'
down_revision: Union[str, Sequence[str], None] = 'f77b45958907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("books") as batch_op:
        # Move all add/drop operations INSIDE the batch block
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_column('author')
        
        batch_op.create_foreign_key(
            "fk_books_author",
            "authors",
            ['author_id'], 
            ['id']
        )
        batch_op.create_foreign_key(
            "fk_books_category",
            "categories",
            ['category_id'], 
            ['id']
        )

def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("books") as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))
        
        # Name the constraints explicitly so they can be dropped properly
        batch_op.drop_constraint('fk_books_author', type_='foreignkey')
        batch_op.drop_constraint('fk_books_category', type_='foreignkey')
        
        batch_op.drop_column('category_id')
        batch_op.drop_column('author_id')



# def upgrade() -> None:
    
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     # op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
#     # op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=True))
#     op.drop_column('books', 'author')
#     with op.batch_alter_table("books") as batch_op:
#         batch_op.create_foreign_key(
#             "fk_books_author",
#             "authors",
#             ['author_id'], 
#             ['id']
#         )
#         batch_op.create_foreign_key(
#             "fk_books_category",
#             "categories",
#             ['category_id'], 
#             ['id']
#         )
    
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=True))
#     op.drop_constraint(None, 'books', type_='foreignkey')
#     op.drop_constraint(None, 'books', type_='foreignkey')
#     op.drop_column('books', 'category_id')
#     op.drop_column('books', 'author_id')
#     # ### end Alembic commands ###
